# 应用全局配置
application:
  name: 平台基础服务
  version: 6.0.1

# 本应用的参数配置
basic:
  test-key: test_value_on_local

# spring 环境配置
spring:
  main: # 支持服务名相同的Feign Client
    allow-bean-definition-overriding: true
  datasource: # mysql 数据源配置
    url: jdbc:mysql://10.4.208.134:3306/sei_basic?characterEncoding=utf8&useSSL=false
    username: sei
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: # jpa 参数配置
    hibernate:
      ddl-auto: none
      namingStrategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  cache: # spring 缓存配置
    redis:
      time-to-live: 20s
  redis: # redis 缓存参数配置
    host: 10.4.208.132
    port: 6379
    password: ZmkDbgaua3Rso33T
    database: 0

# sei 参数配置
sei:
  number-generator-url: http://10.4.208.87:19002/config-center-controller/api